# Generated by Django 4.2.1 on 2023-08-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='customer name')),
                ('customer_phone', models.CharField(max_length=200, verbose_name='customer phone')),
                ('customer_address', models.CharField(max_length=200, verbose_name='customer address')),
                ('pin_code', models.CharField(max_length=100, verbose_name='pin code')),
                ('building_number', models.CharField(max_length=120, verbose_name='building')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=130, verbose_name='state')),
                ('total_price', models.FloatField(verbose_name='total price')),
                ('total_quantity', models.IntegerField(verbose_name='total quantity')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_user', to='users.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
