# Generated by Django 4.2.1 on 2023-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=300, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('token', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='token')),
                ('token_expires', models.DateTimeField(blank=True, null=True, verbose_name='token expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updation date')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
